Fixed tipping ownself bug.
BitcoinAmiens/dogecoin-tipping-bot pull request #38
Opened 2018-03-28 15:46 UTC by dragonhuntr

Fixed the "tipping yourself" bug submitted by @mbaumanndev .

2018-03-28 20:02 UTC, rllola commented
Thank you !

I added a comment. If you can modify it I will then be able to merge it.

Also if you have a Dogecoin address for tipping ;)

2018-03-28 20:03 UTC, rllola requested changes

2018-03-28 20:03 UTC, rllola commented on src/commands/tip.js
> +  if (fromAccount == toAccount) {
In javascript we usually use `===` to check equality.

2018-03-30 02:09 UTC, dragonhuntr commented
Done, missed an = there ;D

2018-03-31 18:46 UTC, rllola approved these changes

2018-03-31 18:46 UTC, merged